import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import Nav from '@/components/nav/Nav'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  fallback: ['Helvetica', 'Arial', 'sans-serif'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
